# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fee1a60bcf9e8f1f4ef411246edd7fa7defc07227c9a2ee2b8d08a87edb58f79a2cd7790cc4d37c66484b6d8d8b8235fc8174d35c0f4469f6f0d3bb4a5e7de3

test:
  secret_key_base: ee2a4fb7a3ac9f7b3ce96264ab352c81a93f5634c2613b5c7eefb538e45a37b8fed5eeda313df85573131a1e3690e27a25551c4fc71a0f551362659be7c459a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
